### PR TITLE
Removed git submodule.

### PR DESCRIPTION
**Pull request by wil-langford**

### CODE REVIEW

**Comment by Austin-Williams** [comment]
I literally don't understand anything on the page that links to.

**Comment by wil-langford** [comment]
If you have a few minutes and a reasonable connection, I'm pretty sure my
video chat is working now.


On Tue, Jun 9, 2015 at 9:54 PM, Austin Williams <notifications@github.com>
wrote:

> I literally don't understand anything on the page that links to.
>
> On Tue, Jun 9, 2015 at 9:51 PM, Wil Langford <notifications@github.com>
> wrote:
>
> > Merged #2 <https://github.com/Austin-Williams/3x3-game-taxonomy/pull/2>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Austin-Williams/3x3-game-taxonomy/pull/2#event-327026839
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Austin-Williams/3x3-game-taxonomy/pull/2#issuecomment-110588297>
> .
>



-- 
An apple every 20 minutes keeps 72 doctors away.

**Comment by Austin-Williams** [comment]
I have a decent connection, but no mic right now... and i'm right next to a
loud bar (I live outside now and I slurp free wifi from different places
depending on the weather, their open hours, etc etc).

However, I DO have a mic back at my motorcycle, which I'll start keeping in
my backpack so we can vid chat next time (probably after Sunday, I'm going
on a camping trip with a friend from Thursday to Sunday).

**Comment by wil-langford** [comment]
Ok.  Good hunting on the wifi front.  :)

On Tue, Jun 9, 2015 at 10:05 PM, Austin Williams <notifications@github.com>
wrote:

> I have a decent connection, but no mic right now... and i'm right next to a
> loud bar (I live outside now and I slurp free wifi from different places
> depending on the weather, their open hours, etc etc).
>
> However, I DO have a mic back at my motorcycle, which I'll start keeping in
> my backpack so we can vid chat next time (probably after Sunday, I'm going
> on a camping trip with a friend from Thursday to Sunday).
>
> On Tue, Jun 9, 2015 at 10:00 PM, Wil Langford <notifications@github.com>
> wrote:
>
> > If you have a few minutes and a reasonable connection, I'm pretty sure my
> > video chat is working now.
> >
> >
> > On Tue, Jun 9, 2015 at 9:54 PM, Austin Williams <
> notifications@github.com>
> > wrote:
> >
> > > I literally don't understand anything on the page that links to.
> > >
> > > On Tue, Jun 9, 2015 at 9:51 PM, Wil Langford <notifications@github.com
> >
> > > wrote:
> > >
> > > > Merged #2 <
> https://github.com/Austin-Williams/3x3-game-taxonomy/pull/2
> > >.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/Austin-Williams/3x3-game-taxonomy/pull/2#event-327026839
> > > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/Austin-Williams/3x3-game-taxonomy/pull/2#issuecomment-110588297
> > >
> > > .
> > >
> >
> >
> >
> > --
> > An apple every 20 minutes keeps 72 doctors away.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Austin-Williams/3x3-game-taxonomy/pull/2#issuecomment-110589122
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Austin-Williams/3x3-game-taxonomy/pull/2#issuecomment-110590393>
> .
>



-- 
An apple every 20 minutes keeps 72 doctors away.

**Comment by Austin-Williams** [comment]
It's not liking life:

>>> import game2p3s as g
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "game2p3s.py", line 5, in <module>
    import lukmdo_lehmer.lehmer as lehmer
ImportError: No module named lehmer

**Comment by wil-langford** [comment]
There should be two files in the lukmdo_lehmer directory:

lehmer.py (attached to a previous email)
__init__.py (empty file created by you)

If lehmer.py is missing, look for it on the email I sent a little while
ago.  If __init__.py is missing, create it with "touch __init__.py".

On Tue, Jun 9, 2015 at 10:12 PM, Austin Williams <notifications@github.com>
wrote:

> It's not liking life:
>
> >>> import game2p3s as g
> Traceback (most recent call last):
> File "<stdin>", line 1, in <module>
> File "game2p3s.py", line 5, in <module>
> import lukmdo_lehmer.lehmer as lehmer
> ImportError: No module named lehmer
>
>
> On Tue, Jun 9, 2015 at 10:07 PM, Wil Langford <notifications@github.com>
>
> wrote:
>
> > Ok. Good hunting on the wifi front. :)
> >
> > On Tue, Jun 9, 2015 at 10:05 PM, Austin Williams <
> notifications@github.com
> > >
> > wrote:
> >
> > > I have a decent connection, but no mic right now... and i'm right next
> > to a
> > > loud bar (I live outside now and I slurp free wifi from different
> places
> > > depending on the weather, their open hours, etc etc).
> > >
> > > However, I DO have a mic back at my motorcycle, which I'll start
> keeping
> > in
> > > my backpack so we can vid chat next time (probably after Sunday, I'm
> > going
> > > on a camping trip with a friend from Thursday to Sunday).
> > >
> > > On Tue, Jun 9, 2015 at 10:00 PM, Wil Langford <
> notifications@github.com>
> > > wrote:
> > >
> > > > If you have a few minutes and a reasonable connection, I'm pretty
> sure
> > my
> > > > video chat is working now.
> > > >
> > > >
> > > > On Tue, Jun 9, 2015 at 9:54 PM, Austin Williams <
> > > notifications@github.com>
> > > > wrote:
> > > >
> > > > > I literally don't understand anything on the page that links to.
> > > > >
> > > > > On Tue, Jun 9, 2015 at 9:51 PM, Wil Langford <
> > notifications@github.com
> > > >
> > > > > wrote:
> > > > >
> > > > > > Merged #2 <
> > > https://github.com/Austin-Williams/3x3-game-taxonomy/pull/2
> > > > >.
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > > > >
> > > >
> > >
> >
> https://github.com/Austin-Williams/3x3-game-taxonomy/pull/2#event-327026839
> > > > > >
> > > > > > .
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > >
> > >
> >
> https://github.com/Austin-Williams/3x3-game-taxonomy/pull/2#issuecomment-110588297
> > > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > An apple every 20 minutes keeps 72 doctors away.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/Austin-Williams/3x3-game-taxonomy/pull/2#issuecomment-110589122
> > > >
> > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/Austin-Williams/3x3-game-taxonomy/pull/2#issuecomment-110590393
> > >
> > > .
> > >
> >
> >
> >
> > --
> > An apple every 20 minutes keeps 72 doctors away.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Austin-Williams/3x3-game-taxonomy/pull/2#issuecomment-110590571
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Austin-Williams/3x3-game-taxonomy/pull/2#issuecomment-110591815>
> .
>



-- 
An apple every 20 minutes keeps 72 doctors away.

**Comment by Austin-Williams** [comment]
oh. I thought I was supposed to create a file called __init__.py and *enter
the contents of lehmer.py into it...

hold on.... I'm going to remove my palm from my face so I can fix that....

**Pull request merged**
